#!/bin/bash
export PATH="$HOME/.jenv/bin:$PATH"

JAVA_VERSION_LIST=()
JAVA_VERSION_LIST+=('openjdk@11')
JAVA_VERSION_LIST+=('openjdk@17')
JAVA_VERSION_LIST+=('openjdk@19')


# jenv
brew install jenv

# install via brew
for JAVA_VERSION in ${JAVA_VERSION_LIST[@]};
do
    brew install ${JAVA_VERSION}
done


echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(jenv init -)"' >> ~/.bashrc
echo 'jenv enable-plugin export' >> ~/.bashrc

# setup jenv
cd /Library/Java/JavaVirtualMachines/; ls | xargs -I {} jenv add /Library/Java/JavaVirtualMachines/{}/Contents/Home

# set default
jenv global 14.0
