#!/bin/bash

NODE_LATEST_VERSION=""

brew install nodenv
eval "$(nodenv init -)"
NODE_LATEST_VERSION="$(nodenv install --list | grep -v - | grep -v b | grep -v [A-Za-z] | tail -1 | xargs echo)"

nodenv install "${NODE_LATEST_VERSION}"
