#!/bin/bash

source ./install-brew

# languages
source ./install-python
source ./install-java
source ./install-node

# java web tools
source ./install-maven

# frameworks
source ./install-android

# tools
source ./install-hammerspoon
source ./install-spectacle

# editors
source ./install-atom
