#!/bin/bash

JAVA_VERSION_LIST=()
JAVA_VERSION_LIST+=('adoptopenjdk8')
JAVA_VERSION_LIST+=('adoptopenjdk9')
JAVA_VERSION_LIST+=('adoptopenjdk10')
JAVA_VERSION_LIST+=('adoptopenjdk11')
JAVA_VERSION_LIST+=('adoptopenjdk12')
JAVA_VERSION_LIST+=('adoptopenjdk13')

brew tap AdoptOpenJDK/openjdk

for JAVA_VERSION in ${JAVA_VERSION_LIST[@]};
do
    brew cask install ${JAVA_VERSION}
done