#!/bin/bash

source ./install-brew

# languages
source ./install-python
source ./install-java
source ./install-node
source ./install-rbenv

# java web tools
source ./install-maven

# frameworks
source ./install-android

# tools
source ./install-hammerspoon
source ./install-spectacle
source ./install-cloudapp

# editors
source ./install-atom
